NEXT-20396 - Remove StoreApiProxy usage from storefront scope
shopware/e2e-testsuite-platform pull request #228
Opened 2022-05-31 13:33 UTC by keulinho

We want to deprecate and then remove the StoreApiProxy from the Storefront proxy as it makes regularly problems and is just a shortcut to creating own custom controllers.

So we remove the proxy usage here and use the store-api directly

2022-05-31 13:34 UTC, keulinho commented
This fix is needed for https://gitlab.shopware.com/shopware/6/product/platform/-/merge_requests/8210

2022-05-31 14:17 UTC, seggewiss requested changes
- Why is the SalesChannelAccess no longer required?
- Please adjust the package.json Version to a new Bugfix release

2022-06-01 05:58 UTC, keulinho commented
@seggewiss the `storefrontApiRequest` command does the fetching of the access key for the sales channel internally 
it looks like this:
```js
Cypress.Commands.add('storefrontApiRequest', (method, endpoint, header = {}, body = {}) => {
    return cy.getSalesChannelId().then((salesChannelAccessKey) => {
        const requestConfig = {
            headers: {
                'SW-Access-Key': salesChannelAccessKey,
                ...header
            },
            body: {
                ...body
            },
            method: method,
            url: `/store-api/${endpoint}`
        };

        return cy.request(requestConfig).then((result) => {
            return result.body.data;
        });
    });
});
```

Honestly the naming is quite weird as all that it does is do a store-api request, as there is no (and never was a storefront api :rofl: ) but i guess renaming that would be a major break right?

2022-06-01 07:43 UTC, seggewiss approved these changes
LGTM!

2022-06-07 06:03 UTC, jleifeld approved these changes

2022-06-07 06:04 UTC, merged