Migrate to store-api
shopware/e2e-testsuite-platform pull request #57
Opened 2020-11-02 13:46 UTC by shyim

2020-11-10 09:11 UTC, klarstil requested changes

2020-11-10 09:11 UTC, klarstil commented on cypress/support/service/saleschannel/fixture/order.fixture.js
> +                return this.apiClient.setContextToken(response.data['contextToken']);
`response.data.contextToken` - you don't need the array notation here. This is only necessary when the key contains characters like hyphens

2020-11-10 15:23 UTC, klarstil approved these changes

2020-11-13 11:24 UTC, leichteckig approved these changes

2020-11-13 11:25 UTC, merged